### ISSUE TITLE
add text generation apis

### ISSUE THREAD

**Issue by ayoubmrx** [BIGmama-technology/Hyko-toolkit#16]
for example Cohere, Anthropic, Gemini

## Cohere : 
- [x] Text Embedding
- [x] Text generation

## Anthropic : 
- [x] Text generation

## Gemini : 
- [x] Text Embedding
- [x] Text generation

## Huggingface : 

- [x] Text generation

## Groq : 

- [x]  Text generation

## Open-router.ai :

- [x] Text generation

**Comment by 1hachem** [comment]
@ayoubmrx I moved the deadline for this ticket for tmrw inchalah so you get a chance to add the `openrouter.ai` api
