### ISSUE TITLE
Sending Data Outside Blueprint

### ISSUE THREAD

**Issue by Mouhamedtec** [BIGmama-technology/Hyko-toolkit#61]
Salam,
@1hachem 
I encountered an issue where I needed to send data outside (Exporting) my Blueprint so that I could manipulate it later. To resolve this, I thoroughly reviewed the toolkit functions, utils, and models. As a result, I’ve developed new utilities to address this issue.

I’d like to contribute these changes by submitting a pull request. Could you please review my proposed solution?

**Comment by 1hachem** [comment]
Salam alikom @Mouhamedtec, happy to see people contributing to hyko, yes please go ahead and open a pr with your changes ! 🚀
